const equipmentData = [
  {
    "type": "Altice One ECM",
    "addressable": "No",
    "format": "N/A",
    "status": "A",
    "equipType": ["50-Altice 1 Modem"],
    "manufacturer": ["UNKNOWN"],
    "location": ["Z-DefaultOutlet"],
    "rates": "OOL and speed rates",
    "eventsNvod": "N/N",
  },
  {
    "type": "Altice One Main",
    "addressable": "Yes",
    "format": ["4"],
    "status": "A",
    "equipType": ["20-Sagemcom Altice 1"],
    "manufacturer": ["UNKNOWN"],
    "location": ["Z-DefaultOutlet"],
    "rates": "14",
    "eventsNvod": "Y/N",
  },
  {
    "type": "Altice One Mini",
    "addressable": "Yes",
    "format": ["4"],
    "status": "A",
    "equipType": ["21-Sagemcom Mini Box"],
    "manufacturer": ["UNKNOWN"],
    "location": ["Z-DefaultOutlet"],
    "rates": "13",
    "eventsNvod": "Y/N",
    
  },
  {
    "type": "Altice One Router",
    "addressable": "No",
    "format": "N/A",
    "status": "A",
    "equipType": ["33-Altice 1 Router"],
    "manufacturer": ["UNKNOWN"],
    "location": ["Z-DefaultOutlet"],
    "rates": "A6",
    "eventsNvod": "N/N",
    
  },
  {
    "type": "CableCard (PowerKey)",
    "addressable": "Yes",
    "format": ["1"],
    "status": "B",
    "equipType": ["61-Pkey M-CableCard"],
    "manufacturer": ["C - S/A"],
    "location": ["N (CableCard)"],
    "rates": "MU",
    "eventsNvod": "Y/N",
    
  },
  {
    "type": "Fiber Gateway",
    "addressable": "No",
    "format": "N/A",
    "status": "B",
    "equipType": ["65 ONT Gate (Gen 7)"],
    "manufacturer": ["UNKNOWN"],
    "location": ["Z-DefaultOutlet"],
    "rates": "F. or 8H or D2",
    "eventsNvod": "N/N",
    
  },
  {
    "type": "IPT (Telephone number)",
    "addressable": "No",
    "format": "N/A",
    "status": "A",
    "equipType": ["81 ONT Gate (Gen 8)", "15-IPT (native)"],
    "manufacturer": ["UNKNOWN"],
    "location": ["T-IPT (native)", "P-Ported IPT"],
    "rates": "OV rate code",
    "eventsNvod": "N/N",
    
  },
  {
    "type": "Modem",
    "addressable": "No",
    "format": "N/A",
    "status": "A",
    "equipType": ["52-OOL Modem", "53-OV Modem", "69-Docsis 3.0", "84-Cust Modem"],
    "manufacturer": ["UNKNOWN"],
    "location": ["5-OV Modem"],
    "rates": "CM (if Optimum Owned)",
    "eventsNvod": "N/N",
    
  },
  {
    "type": "Range Extender",
    "addressable": "No",
    "format": "N/A",
    "status": "A",
    "equipType": ["73-Smart WiFi Extender"],
    "manufacturer": ["UNKNOWN"],
    "location": ["W-RangeExtender"],
    "rates": "3",
    "eventsNvod": "N/N",
    
  },
  {
    "type": "Samsung Box Host ID",
    "addressable": "No",
    "format": "N/A",
    "status": "A",
    "equipType": ["96-SMT-C5320"],
    "manufacturer": ["Samsung-JCA"],
    "location": ["M-JCA Equip"],
    "rates": "3E",
    "eventsNvod": "N/N",
    
  },
  {
    "type": "Samsung Box JCAS ID",
    "addressable": "Yes",
    "format": ["8"],
    "status": "A",
    "equipType": ["95-JCA ID"],
    "manufacturer": ["Samsung-JCA"],
    "location": ["I-JCA ID"],
    "rates": "98",
    "eventsNvod": "Y/N",
    
  },
  {
    "type": "Scientific Atlanta Box",
    "addressable": "Yes",
    "format": ["C (NDS)", "1 (PowerKey)"],
    "status": "B",
    "equipType": ["25-29-42XX Series", "45-8300 SD", "47-8300 HD"],
    "manufacturer": ["S - S/A"],
    "location": ["E-S/A Digital"],
    "rates": "H-High Def Eq",
    "eventsNvod": "Y/N",
    
  },
  {
    "type": "Smart Card (NDS)",
    "addressable": "Yes",
    "format": ["1"],
    "status": "B",
    "equipType": ["3-Smart Card"],
    "manufacturer": ["UNKNOWN"],
    "location": ["S-Smart Card NDS"],
    "rates": "98",
    "eventsNvod": "Y/N",
    
  },
  {
    "type": "Smart Router",
    "addressable": "No",
    "format": "N/A",
    "status": "A",
    "equipType": ["32-Router Included"],
    "manufacturer": ["UNKNOWN"],
    "location": ["Z-DefaultOutlet"],
    "rates": "A6",
    "eventsNvod": "N/N",
    
  },
  {
    "type": "Static IP Router",
    "addressable": "No",
    "format": "N/A",
    "status": "A",
    "equipType": ["90-BusinessStaticIP"],
    "manufacturer": ["UNKNOWN"],
    "location": ["L-BStatIP"],
    "rates": "RT",
    "eventsNvod": "N/N",
    
  },
  {
    "type": "Stream device",
    "addressable": "Yes",
    "format": ["4"],
    "status": "A",
    "equipType": ["19-Stream"],
    "manufacturer": ["UNKNOWN"],
    "location": ["Z-DefaultOutlet"],
    "rates": "C4",
    "eventsNvod": "Y/V",
    
  },
  {
    "type": "Tuning Adapter",
    "addressable": "Yes",
    "format": ["C (NDS)", "1 (PowerKey)"],
    "status": "B",
    "equipType": ["62-Tuning Adapter"],
    "manufacturer": ["UNKNOWN"],
    "location": ["G-Tuning Adapter"],
    "rates": "AD",
    "eventsNvod": "Y/N",
    
  },
  {
    "type": "Ubee Gateway",
    "addressable": "No",
    "format": "N/A",
    "status": "A",
    "equipType": ["67-3.1 Gateway"],
    "manufacturer": ["UNKNOWN"],
    "location": ["Z-DefaultOutlet"],
    "rates": "UM",
    "eventsNvod": "N/N",
    
  }
];